[k3s_servers]
# K3s server nodes (control plane)
hlab-k3s-srv-01 ansible_host=10.0.10.50
hlab-k3s-srv-02 ansible_host=10.0.10.51
hlab-k3s-srv-03 ansible_host=10.0.10.52

[k3s_workers]
# K3s worker nodes
hlab-k3s-wkr-01 ansible_host=192.168.1.120
hlab-k3s-wkr-02 ansible_host=192.168.1.121
hlab-k3s-wkr-03 ansible_host=192.168.1.122

[docker_managers]
# Docker Swarm manager nodes
hlab-swarm-mgr-01 ansible_host=192.168.1.130
hlab-swarm-mgr-02 ansible_host=192.168.1.131

[docker_workers]
# Docker Swarm worker nodes
hlab-swarm-wkr-01 ansible_host=192.168.1.135
hlab-swarm-wkr-02 ansible_host=192.168.1.136

[docker_swarm:children]
docker_managers
docker_workers

[media_servers]
# Media service servers
hlab-plex-01 ansible_host=192.168.1.140
hlab-jellyfin-01 ansible_host=192.168.1.141
hlab-arr-01 ansible_host=192.168.1.142

[all:vars]
# Global variables
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
k3s_cluster_token=secure-random-token-change-me
