---
- name: Configure Docker Swarm Cluster
  hosts: docker_swarm
  become: yes
  vars:
    swarm_advertise_addr: "{{ ansible_default_ipv4.address }}"
    
  tasks:
    - name: Initialize Docker Swarm on first manager
      docker_swarm:
        state: present
        advertise_addr: "{{ swarm_advertise_addr }}"
      when: inventory_hostname == groups['docker_managers'][0]
      register: swarm_info

    - name: Get worker join token
      docker_swarm_info:
      register: swarm_facts
      when: inventory_hostname == groups['docker_managers'][0]

    - name: Set worker join token fact
      set_fact:
        worker_token: "{{ swarm_facts.swarm_facts.JoinTokens.Worker }}"
        manager_token: "{{ swarm_facts.swarm_facts.JoinTokens.Manager }}"
        swarm_manager_addr: "{{ hostvars[groups['docker_managers'][0]]['ansible_default_ipv4']['address'] }}"
      when: inventory_hostname == groups['docker_managers'][0]

    - name: Share tokens with other nodes
      set_fact:
        worker_token: "{{ hostvars[groups['docker_managers'][0]]['worker_token'] }}"
        manager_token: "{{ hostvars[groups['docker_managers'][0]]['manager_token'] }}"
        swarm_manager_addr: "{{ hostvars[groups['docker_managers'][0]]['swarm_manager_addr'] }}"
      when: inventory_hostname != groups['docker_managers'][0]

    - name: Join additional managers to swarm
      docker_swarm:
        state: join
        advertise_addr: "{{ swarm_advertise_addr }}"
        join_token: "{{ manager_token }}"
        remote_addrs: ["{{ swarm_manager_addr }}:2377"]
      when: 
        - inventory_hostname != groups['docker_managers'][0]
        - inventory_hostname in groups['docker_managers']

    - name: Join workers to swarm
      docker_swarm:
        state: join
        advertise_addr: "{{ swarm_advertise_addr }}"
        join_token: "{{ worker_token }}"
        remote_addrs: ["{{ swarm_manager_addr }}:2377"]
      when: inventory_hostname in groups['docker_workers']

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
